Add UserId, RoomId, and Role types
Parnassius/cerbottana pull request #96
Opened 2020-10-16 17:23 UTC by Parnassius

Also move TiersDict definition from connection.py

2020-10-16 17:25 UTC, Parnassius commented
@palt0 vedi per caso qualcosa che non ti quadra?

2020-10-16 17:25 UTC, Parnassius commented
Closes #76

2020-10-17 13:26 UTC, palt0 requested changes
A cerbottana filtra correttamente comandi richiesti da utenti regular? Nel mio test non lo faceva.

A parte i commenti che ho lasciato per `has_role`, potremmo considerare l'idea di aggiungere anche `JsonDict` di `ŧcg.py` in `typedefs.py`. È chiaramente un tipo generico non specifico del TCG, ma possiamo tranquillamente spostarlo in futuro quando servirà in un altro modulo.

Gran bel lavoro, però!

2020-10-17 13:26 UTC, palt0 commented on utils.py
> +        if role == "voice" and not strict_voice_check and user[0] not in "*★☆^":
Ho due cose da osservare con `strict_voice_check == False`.

" " è il rank nativo associato ai regular user e va quindi aggiunto ai simboli da escludere.

Vanno esclusi anche i caratteri alfanumerici, perché `has_role` viene invocato anche dall'handler di `|queryresponse|userdetails|` per parsare il dizionario `rooms`:
```
|queryresponse|userdetails|{"id":"armastrong","userid":"armastrong","name":"ArmAstrong","avatar":101,"group":" ","autoconfirmed":false,"status":"","rooms":{"italiano":{},"☆battle-gen5randombattle-1204635570":{"p1":" NOMYLOVE","p2":" ArmAstrong"}}}
```
A differenza di quanto succede per i log della chat, se un utente non è auth in una room non viene lasciato uno spazio prima del roomid e quindi `user[0]` diventa la prima lettera del roomid!

Questa è una possibile modifica:
```suggestion
        if (
            role == "voice"
            and not strict_voice_check
            and user[0] not in " *★☆^"
            and not user[0].isalpha()
        ):
```

2020-10-17 13:26 UTC, palt0 commented on tests/test_roles.py
> +        ("voice", "", False),
Manca il test per gli utenti regular (che fallirebbe, vd. commento successivo).
```suggestion
        ("voice", "^", False),
        ("voice", " ", False),
        ("voice", "", False),
```

2020-10-17 13:39 UTC, palt0 commented on utils.py
>          user (str): User to check.
Ah, poi c'è anche da aggiornare la docstring includendo `strict_voice_check`. Attento che con i parametri opzionali le Google docstring hanno una sintassi un po' particolare, dai un occhio a qualcosa che ho scritto per il models refactor.

2020-10-17 14:27 UTC, palt0 reviewed
Mi fido che le modifiche siano equivalenti alle mie, sembra di sì, e in caso non ho ulteriori commenti.

2020-10-17 14:28 UTC, palt0 approved these changes
Ok

2020-10-17 14:37 UTC, merged